version: "3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
       - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
